package com.hospital.enums;

public enum Role {
    ADMIN,
    DOCTOR,
    NURSE,
    PATIENT,
    BLOOD_BANK_MANAGER,
    ORGAN_DONOR,
    BLOOD_DONOR,
    AMBULANCE_OPERATOR,
    LAB_TECHNICIAN,
    PHARMACIST,
    RECEPTIONIST,
    MEDICAL_SHOP_OWNER,
    DIAGNOSTIC_CENTER_OWNER,
    INDEPENDENT_NURSE,
    PHLEBOTOMIST
}
