-- V3: Doctor Slots, Appointments, Medical Records

-- Doctor Slots
CREATE TABLE IF NOT EXISTS doctor_slots (
    id                    BIGINT AUTO_INCREMENT PRIMARY KEY,
    doctor_id             BIGINT       NOT NULL,
    slot_date             DATE,
    day_of_week           VARCHAR(15),
    start_time            TIME         NOT NULL,
    end_time              TIME         NOT NULL,
    slot_duration_minutes INT          DEFAULT 15,
    max_patients          INT          DEFAULT 1,
    slot_type             VARCHAR(20)  DEFAULT 'SPECIFIC_DATE',
    status                VARCHAR(20)  DEFAULT 'AVAILABLE',
    block_reason          VARCHAR(255),
    is_active             TINYINT(1)   DEFAULT 1,
    created_at            DATETIME     DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_slot_doctor FOREIGN KEY (doctor_id) REFERENCES doctors(id),
    UNIQUE KEY uq_slot_datetime (doctor_id, slot_date, start_time)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Appointments
CREATE TABLE IF NOT EXISTS appointments (
    id                   BIGINT AUTO_INCREMENT PRIMARY KEY,
    appointment_number   VARCHAR(30)    NOT NULL UNIQUE,
    patient_id           BIGINT         NOT NULL,
    doctor_id            BIGINT         NOT NULL,
    department_id        BIGINT         NOT NULL,
    branch_id            BIGINT         NOT NULL,
    slot_id              BIGINT,
    appointment_date     DATE           NOT NULL,
    appointment_time     TIME           NOT NULL,
    type                 VARCHAR(20)    DEFAULT 'IN_PERSON',
    status               VARCHAR(20)    DEFAULT 'PENDING',
    symptoms             TEXT,
    notes                TEXT,
    doctor_notes         TEXT,
    rejection_reason     VARCHAR(500),
    consultation_fee     DECIMAL(10,2),
    is_paid              TINYINT(1)     DEFAULT 0,
    payment_id           VARCHAR(100),
    is_emergency         TINYINT(1)     DEFAULT 0,
    follow_up_date       DATE,
    approved_by          BIGINT,
    approved_at          DATETIME,
    created_at           DATETIME       DEFAULT CURRENT_TIMESTAMP,
    updated_at           DATETIME       DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT fk_appt_patient    FOREIGN KEY (patient_id)    REFERENCES patients(id),
    CONSTRAINT fk_appt_doctor     FOREIGN KEY (doctor_id)     REFERENCES doctors(id),
    CONSTRAINT fk_appt_dept       FOREIGN KEY (department_id) REFERENCES departments(id),
    CONSTRAINT fk_appt_branch     FOREIGN KEY (branch_id)     REFERENCES hospital_branches(id),
    CONSTRAINT fk_appt_slot       FOREIGN KEY (slot_id)       REFERENCES doctor_slots(id),
    CONSTRAINT fk_appt_approved   FOREIGN KEY (approved_by)   REFERENCES users(id),
    INDEX idx_appt_doctor_date   (doctor_id,  appointment_date),
    INDEX idx_appt_patient       (patient_id),
    INDEX idx_appt_status        (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Medical Records
CREATE TABLE IF NOT EXISTS medical_records (
    id                BIGINT AUTO_INCREMENT PRIMARY KEY,
    patient_id        BIGINT       NOT NULL,
    doctor_id         BIGINT       NOT NULL,
    appointment_id    BIGINT,
    visit_date        DATE         NOT NULL,
    diagnosis         TEXT,
    symptoms          TEXT,
    treatment         TEXT,
    prescription      TEXT,
    follow_up_date    DATE,
    follow_up_notes   TEXT,
    blood_pressure    VARCHAR(20),
    heart_rate        INT,
    temperature       DECIMAL(4,1),
    weight            DECIMAL(5,2),
    height            DECIMAL(5,2),
    oxygen_saturation DECIMAL(5,2),
    is_confidential   TINYINT(1)   DEFAULT 0,
    created_at        DATETIME     DEFAULT CURRENT_TIMESTAMP,
    updated_at        DATETIME     DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT fk_record_patient     FOREIGN KEY (patient_id)     REFERENCES patients(id),
    CONSTRAINT fk_record_doctor      FOREIGN KEY (doctor_id)      REFERENCES doctors(id),
    CONSTRAINT fk_record_appointment FOREIGN KEY (appointment_id) REFERENCES appointments(id),
    INDEX idx_record_patient (patient_id),
    INDEX idx_record_doctor  (doctor_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
